[package]
name = "red_black_tree"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
rand="0.9.1"
criterion = "0.6.0"
rbtree = "0.1.7"

[profile.bench]
debug = false

[[bench]]
name = "compare_rbtree"
harness = false
